### ISSUE TITLE
DisableSensor should disable proximity monitor (iOS)

### ISSUE THREAD

**Issue by puneethrai** [awoken-well/cordova-plugin-proximity#7]
Hey,

Issue: When calling disableSensor you are just removing observer but not stoping the monitor in iOS devices . This will still make iOS devices go to black screen when proximity is near.

Recommendation: add this code in stop method
` [[UIDevice currentDevice] setProximityMonitoringEnabled:NO];`
so that we stop monitoring the device there by disabling the proximity

**Comment by olafjanssen** [comment]
Hi Puneethrai,
I can't believe I missed that! Thanks for paying attention and informing me with the solution.
I just fixed the issue on the repo.

**Comment by pamo85** [comment]
can you please publish fix to plugin.cordova. thx

**Comment by olafjanssen** [comment]
It's re-published! Thanks for reminding me.
