### ISSUE TITLE
Turn Off Screen on Android

### ISSUE THREAD

**Issue by lylepratt** [awoken-well/cordova-plugin-proximity#9]
Is there a way to use this plugin to also completely turn off the screen on Android devices (like iOS does automatically)?

**Comment by olafjanssen** [comment]
I could put it in the plugin as a feature. In the meantime you could easily combine this plugin with one that does screen dimming such as: https://github.com/alunny/ScreenDim

**Comment by lylepratt** [comment]
Hi! Yes I found that plugin, but it doesn't actually turn off the screen. It just disables the screen dim TIMER, preventing the screen from automatically being dimmed.

**Comment by olafjanssen** [comment]
Hmm... it seems that it should be possible:
http://stackoverflow.com/questions/21884181/turn-off-screen-programmatically-when-face-is-close-the-screen-on-android

I'm extremely busy this week but I might try to get it working some time next week.. feel free to fork and try it for yourself :)

**Comment by lylepratt** [comment]
Cool thanks for the link! Will try to steal some time later in the week.

**Comment by warthog618** [comment]
There is already a fork that provides this functionality - https://github.com/rbarroetavena/cordova-plugin-proximity.git.

Perhaps you could pull the feature from that fork?

**Comment by olafjanssen** [comment]
Merged with spheroid- fork changes.
